# fly.toml file generated for mojo-learning-labs1 on 2023-03-21T12:54:19+01:00

app = "mojo-learning-labs1"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "iad"
processes = []

[env]

[experimental]
  auto_rollback = true

[[services]]

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
